/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PumpFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "benefeciary"
      | "changeBenefeciary"
      | "changeFee"
      | "deployTokenAndInternalSwap"
      | "deposit"
      | "fee"
      | "mapTokensToSwap"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
      | "uniswapRouter"
      | "weth"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "InternalSwapDeployed" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "benefeciary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "changeBenefeciary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "changeFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deployTokenAndInternalSwap",
    values: [string, string, string, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(functionFragment: "fee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "mapTokensToSwap",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapRouter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "weth", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "benefeciary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeBenefeciary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "changeFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployTokenAndInternalSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mapTokensToSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "weth", data: BytesLike): Result;
}

export namespace InternalSwapDeployedEvent {
  export type InputTuple = [
    swapContract: AddressLike,
    userToken: AddressLike,
    owner: AddressLike,
    name: string,
    symbol: string,
    initialSupply: BigNumberish,
    twitter: string,
    telegram: string,
    website: string,
    imageUri: string,
    from: AddressLike
  ];
  export type OutputTuple = [
    swapContract: string,
    userToken: string,
    owner: string,
    name: string,
    symbol: string,
    initialSupply: bigint,
    twitter: string,
    telegram: string,
    website: string,
    imageUri: string,
    from: string
  ];
  export interface OutputObject {
    swapContract: string;
    userToken: string;
    owner: string;
    name: string;
    symbol: string;
    initialSupply: bigint;
    twitter: string;
    telegram: string;
    website: string;
    imageUri: string;
    from: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PumpFactory extends BaseContract {
  connect(runner?: ContractRunner | null): PumpFactory;
  waitForDeployment(): Promise<this>;

  interface: PumpFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  benefeciary: TypedContractMethod<[], [string], "view">;

  changeBenefeciary: TypedContractMethod<
    [_benefeciary: AddressLike],
    [void],
    "nonpayable"
  >;

  changeFee: TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;

  deployTokenAndInternalSwap: TypedContractMethod<
    [
      _tokenName: string,
      _tokenSymbol: string,
      _twitter: string,
      _telegram: string,
      _website: string,
      _imageUri: string,
      _liquidityToAdd: BigNumberish
    ],
    [[string, string]],
    "payable"
  >;

  deposit: TypedContractMethod<[], [void], "payable">;

  fee: TypedContractMethod<[], [bigint], "view">;

  mapTokensToSwap: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  uniswapRouter: TypedContractMethod<[], [string], "view">;

  weth: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "benefeciary"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "changeBenefeciary"
  ): TypedContractMethod<[_benefeciary: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "changeFee"
  ): TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deployTokenAndInternalSwap"
  ): TypedContractMethod<
    [
      _tokenName: string,
      _tokenSymbol: string,
      _twitter: string,
      _telegram: string,
      _website: string,
      _imageUri: string,
      _liquidityToAdd: BigNumberish
    ],
    [[string, string]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "fee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mapTokensToSwap"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "uniswapRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "weth"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "InternalSwapDeployed"
  ): TypedContractEvent<
    InternalSwapDeployedEvent.InputTuple,
    InternalSwapDeployedEvent.OutputTuple,
    InternalSwapDeployedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "InternalSwapDeployed(address,address,address,string,string,uint256,string,string,string,string,address)": TypedContractEvent<
      InternalSwapDeployedEvent.InputTuple,
      InternalSwapDeployedEvent.OutputTuple,
      InternalSwapDeployedEvent.OutputObject
    >;
    InternalSwapDeployed: TypedContractEvent<
      InternalSwapDeployedEvent.InputTuple,
      InternalSwapDeployedEvent.OutputTuple,
      InternalSwapDeployedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
