/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface InternalSwapInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addUserTokenReserve"
      | "addWethReserve"
      | "feeBps"
      | "getK"
      | "initialSupply"
      | "listToken"
      | "owner"
      | "removeUserTokenReserve"
      | "removeWethReserve"
      | "renounceOwnership"
      | "reserveUserToken"
      | "reserveWeth"
      | "setMinBps"
      | "swapUserTokenToWeth"
      | "swapWethToUserToken"
      | "transferOwnership"
      | "uniswapPair"
      | "uniswapRouter"
      | "userToken"
      | "weth"
      | "wethOverUserTokenValueAndPrice"
      | "wethOverUserTokenValueAndPriceFee"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddLiquidity"
      | "OwnershipTransferred"
      | "RemoveLiquidity"
      | "Swap"
      | "TokenListed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addUserTokenReserve",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addWethReserve",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "feeBps", values?: undefined): string;
  encodeFunctionData(functionFragment: "getK", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialSupply",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "listToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeUserTokenReserve",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "removeWethReserve",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reserveUserToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reserveWeth",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMinBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapUserTokenToWeth",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapWethToUserToken",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapPair",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapRouter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "userToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "weth", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "wethOverUserTokenValueAndPrice",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "wethOverUserTokenValueAndPriceFee",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addUserTokenReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addWethReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeBps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getK", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initialSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeUserTokenReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeWethReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveUserToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveWeth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setMinBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapUserTokenToWeth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapWethToUserToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "weth", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "wethOverUserTokenValueAndPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wethOverUserTokenValueAndPriceFee",
    data: BytesLike
  ): Result;
}

export namespace AddLiquidityEvent {
  export type InputTuple = [typeReserve: BigNumberish, value: BigNumberish];
  export type OutputTuple = [typeReserve: bigint, value: bigint];
  export interface OutputObject {
    typeReserve: bigint;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemoveLiquidityEvent {
  export type InputTuple = [typeReserve: BigNumberish, value: BigNumberish];
  export type OutputTuple = [typeReserve: bigint, value: bigint];
  export interface OutputObject {
    typeReserve: bigint;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapEvent {
  export type InputTuple = [
    typeSwap: string,
    weth: BigNumberish,
    userToken: BigNumberish,
    price: BigNumberish,
    tokenAddress: AddressLike,
    from: AddressLike
  ];
  export type OutputTuple = [
    typeSwap: string,
    weth: bigint,
    userToken: bigint,
    price: bigint,
    tokenAddress: string,
    from: string
  ];
  export interface OutputObject {
    typeSwap: string;
    weth: bigint;
    userToken: bigint;
    price: bigint;
    tokenAddress: string;
    from: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenListedEvent {
  export type InputTuple = [pair: AddressLike];
  export type OutputTuple = [pair: string];
  export interface OutputObject {
    pair: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InternalSwap extends BaseContract {
  connect(runner?: ContractRunner | null): InternalSwap;
  waitForDeployment(): Promise<this>;

  interface: InternalSwapInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addUserTokenReserve: TypedContractMethod<
    [_userTokenIn: BigNumberish],
    [void],
    "nonpayable"
  >;

  addWethReserve: TypedContractMethod<
    [_wethIn: BigNumberish],
    [void],
    "payable"
  >;

  feeBps: TypedContractMethod<[], [bigint], "view">;

  getK: TypedContractMethod<[], [bigint], "view">;

  initialSupply: TypedContractMethod<[], [bigint], "view">;

  listToken: TypedContractMethod<[], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  removeUserTokenReserve: TypedContractMethod<
    [_userTokenIn: BigNumberish, _rebalance: boolean],
    [void],
    "nonpayable"
  >;

  removeWethReserve: TypedContractMethod<
    [_wethIn: BigNumberish, _rebalance: boolean],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reserveUserToken: TypedContractMethod<[], [bigint], "view">;

  reserveWeth: TypedContractMethod<[], [bigint], "view">;

  setMinBps: TypedContractMethod<[_newBps: BigNumberish], [void], "nonpayable">;

  swapUserTokenToWeth: TypedContractMethod<
    [_userTokenIn: BigNumberish, _wethOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  swapWethToUserToken: TypedContractMethod<
    [_wethIn: BigNumberish, _userTokenOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  uniswapPair: TypedContractMethod<[], [string], "view">;

  uniswapRouter: TypedContractMethod<[], [string], "view">;

  userToken: TypedContractMethod<[], [string], "view">;

  weth: TypedContractMethod<[], [string], "view">;

  wethOverUserTokenValueAndPrice: TypedContractMethod<
    [
      _userTokenIn: BigNumberish,
      _wethIn: BigNumberish,
      _userTokenOut: BigNumberish,
      _wethOut: BigNumberish,
      _isUniswap: boolean
    ],
    [[bigint, bigint]],
    "view"
  >;

  wethOverUserTokenValueAndPriceFee: TypedContractMethod<
    [
      _userTokenIn: BigNumberish,
      _wethIn: BigNumberish,
      _userTokenOut: BigNumberish,
      _wethOut: BigNumberish
    ],
    [[bigint, bigint]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addUserTokenReserve"
  ): TypedContractMethod<[_userTokenIn: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addWethReserve"
  ): TypedContractMethod<[_wethIn: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "feeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getK"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "listToken"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeUserTokenReserve"
  ): TypedContractMethod<
    [_userTokenIn: BigNumberish, _rebalance: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeWethReserve"
  ): TypedContractMethod<
    [_wethIn: BigNumberish, _rebalance: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reserveUserToken"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reserveWeth"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setMinBps"
  ): TypedContractMethod<[_newBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "swapUserTokenToWeth"
  ): TypedContractMethod<
    [_userTokenIn: BigNumberish, _wethOut: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapWethToUserToken"
  ): TypedContractMethod<
    [_wethIn: BigNumberish, _userTokenOut: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "uniswapPair"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "uniswapRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "weth"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "wethOverUserTokenValueAndPrice"
  ): TypedContractMethod<
    [
      _userTokenIn: BigNumberish,
      _wethIn: BigNumberish,
      _userTokenOut: BigNumberish,
      _wethOut: BigNumberish,
      _isUniswap: boolean
    ],
    [[bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "wethOverUserTokenValueAndPriceFee"
  ): TypedContractMethod<
    [
      _userTokenIn: BigNumberish,
      _wethIn: BigNumberish,
      _userTokenOut: BigNumberish,
      _wethOut: BigNumberish
    ],
    [[bigint, bigint]],
    "view"
  >;

  getEvent(
    key: "AddLiquidity"
  ): TypedContractEvent<
    AddLiquidityEvent.InputTuple,
    AddLiquidityEvent.OutputTuple,
    AddLiquidityEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RemoveLiquidity"
  ): TypedContractEvent<
    RemoveLiquidityEvent.InputTuple,
    RemoveLiquidityEvent.OutputTuple,
    RemoveLiquidityEvent.OutputObject
  >;
  getEvent(
    key: "Swap"
  ): TypedContractEvent<
    SwapEvent.InputTuple,
    SwapEvent.OutputTuple,
    SwapEvent.OutputObject
  >;
  getEvent(
    key: "TokenListed"
  ): TypedContractEvent<
    TokenListedEvent.InputTuple,
    TokenListedEvent.OutputTuple,
    TokenListedEvent.OutputObject
  >;

  filters: {
    "AddLiquidity(uint8,uint256)": TypedContractEvent<
      AddLiquidityEvent.InputTuple,
      AddLiquidityEvent.OutputTuple,
      AddLiquidityEvent.OutputObject
    >;
    AddLiquidity: TypedContractEvent<
      AddLiquidityEvent.InputTuple,
      AddLiquidityEvent.OutputTuple,
      AddLiquidityEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RemoveLiquidity(uint8,uint256)": TypedContractEvent<
      RemoveLiquidityEvent.InputTuple,
      RemoveLiquidityEvent.OutputTuple,
      RemoveLiquidityEvent.OutputObject
    >;
    RemoveLiquidity: TypedContractEvent<
      RemoveLiquidityEvent.InputTuple,
      RemoveLiquidityEvent.OutputTuple,
      RemoveLiquidityEvent.OutputObject
    >;

    "Swap(string,uint256,uint256,uint256,address,address)": TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;
    Swap: TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;

    "TokenListed(address)": TypedContractEvent<
      TokenListedEvent.InputTuple,
      TokenListedEvent.OutputTuple,
      TokenListedEvent.OutputObject
    >;
    TokenListed: TypedContractEvent<
      TokenListedEvent.InputTuple,
      TokenListedEvent.OutputTuple,
      TokenListedEvent.OutputObject
    >;
  };
}
